name: backEndDeploy

on:
  push:
    branches:
      - main
jobs:
  deploy-staging:
    name: Deploy to staging
    environment:
      name: Staging
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./api
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY_DEPLOY}}
        heroku_app_name: "ncv-api" #Must be unique in Heroku
        heroku_email: "ncv.application@gmail.com"
        
  deploy-production:
    name: Deploy to production
    environment:
      name: Production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./api
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY_DEPLOY}}
        heroku_app_name: "ncv-production"
        heroku_email: "ncv.application@gmail.com"
