name: Front-end-ci-and-Deploy
on:
  push:
    branches:
      - main
      - thirdIntent

jobs:
  deployDEV:
    name: Deploy-dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

      - name: Preparing Build Directory
        run: npm run build
        env:
          CI: false

      - name: Deployment on Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./web-ui

  deployPROD:
    name: Deploy-prod
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

      - name: Preparing Build Directory
        run: npm run build
        env:
          CI: false

      - name: Deployment on Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./web-ui
