name: Deploy to Firebase
'on':
  push:
    branches:
      - master
      - secondIntent

jobs:

  build_and_deploy_develop:
    name: Deploy to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v1
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN  }}'
          channelId: live
          projectId: ncv-application-desarrollo