name: ONE-DEPLOY
on:
  push:
    branches:
      - secondIntent

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

      - name: Preparing Build Directory
        run: npm run build
        env:
          CI: false

      - name: Deployment on Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting

          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN  }}'
          channelId: live
          projectId: ncv-application-desarrollo
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./web-ui
  